version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    container_name: celery_worker
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"