name: Trigger Terraform Deployment

on:
  push:
    branches:
      - staging-*  # Trigger when committing to any branch starting with staging-
      - prod-*     # Trigger when committing to any branch starting with prod-

jobs:
  trigger-terraform:
    name: Trigger Terraform Repo Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event to Terraform repo
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TERRAFORM_REPO_ACCESS_TOKEN }}" \
          https://api.github.com/repos/jjoby12323/Angoor-JoinTask-Terraform/dispatches \
          -d '{
            "event_type": "deploy_terraform",
            "client_payload": { "branch": "${{ github.ref_name }}" }
          }'